.TH PREY-CONFIG 1 "October 28, 2010"
.SH NAME
prey-config \- configuration tool for Prey
.SH SYNOPSIS
.B prey-config
.br
.SH DESCRIPTION
.B Prey
is a lightweight program that will help you track and find your laptop
if it ever gets stolen.
.PP
.B Prey
comprises a shell script which calls out on a regular basis to
either a server run by prey project, or a url nominated by the system
administrator. A graphical configuration tool is also provided which is
used to maintain the simple config file.
.PP
.B prey-config
is a graphical configuration tool provided to edit the configuration
stored in
.I /etc/prey/config
and after the installation it is available from the
.B Applications
menu.
.br
.SH AUTHOR
Prey was written by Tomas Pollak.
.PP
This manual page was written by Alessio Treglia <alessio@debian.org>,
for the Debian project (but may be used by others).
